name: Testing project.
on:
  - push
  - fork
jobs:
  test:
    name: Testing with franchinette
    runs-on: ubuntu-latest
    steps:
      - name: Installing system dependencies
        run: |
          sudo apt update 
          sudo apt install gcc clang libpq-dev libbsd-dev libncurses-dev valgrind python2-dev python3-pip python3-dev python3-venv python3-wheel -y
      - name: Installing francinette
        run: |
          mkdir temp_____

          cd temp_____ || exit
          rm -rf francinette
          git clone --recursive https://github.com/xicodomingues/francinette.git

          pip3 install wheel
          cp -r francinette "$HOME"
          cd "$HOME" || exit
          rm -rf temp_____
          cd "$HOME"/francinette || exit
          if ! python3 -m venv venv ; then
          	echo "Please make sure than you can create a python virtual environment"
          	echo 'Contact me if you have no idea how to proceed (fsoares- on slack)'
          	exit 1
          fi
          . venv/bin/activate
          if ! pip3 install -r requirements.txt ; then
          	echo 'Problem launching the installer. Contact me (fsoares- on slack)'
          	exit 1
          fi

          RC_FILE="$HOME/.zshrc"
          if ! grep "francinette=" "$RC_FILE" &> /dev/null; then
          	echo "francinette alias not present"
          	printf "\nalias francinette=%s/francinette/tester.sh\n" "$HOME" >> "$RC_FILE"
          fi
          exec "$SHELL"
      - uses: actions/checkout@v4
      - name: Running tests
        run: |
          python3 -m pip install norminette
          ~/francinette/tester.sh
